$kind: http-request
name: Update Task - 200 Success
url: http://localhost:8080/projects/1/tasks/1
method: PUT
body:
  type: json
  content: "{\r

    \    \"status\": \"IN_PROGRESS\",\r

    \    \"priority\": \"LOW\"\r

    }"
auth:
  type: bearer
  credentials:
    token: "{{token}}"
order: 4501851733319931
