spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dmsdb
    username: dmsuser
    password: dmspassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false #ask about this later

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:af3547ee111149fab438fd54398fe7f9d0e56b78c1a2d8b1050f2dd7a6b4a0da}
  expiration: 86400000

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: dms-documents